import type { NextPage } from "next";
import React, { useCallback, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import Link from "next/link";
import { saveAs } from "file-saver";
import RecentImage from "../components/recentImage";

interface Image {
  url: string;
  desc: string;
}

const Home: NextPage = () => {
  const [images, setImages] = useState<Image | null>(null);
  const [isLoading, setLoading] = useState<boolean>(false);
  const [description, setDescription] = useState<string | null>(null);
  const [currImageDesc, setCurrImageDesc] = useState<string | null>(null);
  const [recentImages, setRecentImages] = useState<Image[] | null>(null);

  const fetchGeneratedArt = async (desc: string) => {
    setLoading(true);
    try {
      const res = await fetch("/api", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          description: desc,
        }),
      }).then((res) => res.json());
      setImages(res.image);
      !recentImages
        ? setRecentImages([{ url: res.image.url, desc: desc }])
        : setRecentImages([
            ...recentImages,
            { url: res.image.url, desc: desc },
          ]);
    } catch (err: any) {
      console.log("Something went wrong!");
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateArt = () => {
    if (!description) return;
    setCurrImageDesc(description);
    fetchGeneratedArt(description);
  };

  const handleGenerateArtAgain = () => {
    if (!currImageDesc) return;
    fetchGeneratedArt(currImageDesc);
  };

  const hanldeInputChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      setDescription(e.target.value);
    },
    [description]
  );

  const handleDownloadImage = () => {
    if (images) saveAs(images.url, "yourArt.png");
    return;
  };

  const handleSelectSavedImage = (image: Image) => {
    setImages(image);
    setCurrImageDesc(image.desc);
  };

  useEffect(() => {
    const savedImages = localStorage.getItem("recentImages");
    console.log(savedImages);
    savedImages && setRecentImages(JSON.parse(savedImages));
  }, []);

  useEffect(() => {
    recentImages &&
      localStorage.setItem("recentImages", JSON.stringify(recentImages));
  }, [recentImages]);

  return (
    <div className="w-full min-h-screen">
      <Head>
        <title>AI Art Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="w-full min-h-[50vh] bg-header relative flex flex-row items-center justify-evenly flex-wrap">
        <div className="flex items-center h-full mb-10 mt-10 lg:mb-0 lg:mt-0">
          <div className="flex-1 space-y-14 px-5 flex flex-col items-center fade-in-down">
            <div className="font-black text-3xl text-center text-white">
              CREATE YOUR DIGITAL ART
            </div>
            <div className="w-4/5 md:w-full h-12 bg-white rounded-full p-1 outline outline-offset-8 outline-[2px] outline-white/10 flex flex-row justify-between items-center pl-5">
              <input
                type="text"
                placeholder="Dog in mars"
                className="outline-none md:flex-1 md:pr-3 text-sm md:text-base max-w-[8rem] md:max-w-none"
                onChange={hanldeInputChange}
              />
              <button
                disabled={isLoading || !description}
                onClick={handleGenerateArt}
                className="h-full text-sm md:text-base w-24 px-3 bg-[#111526] rounded-full flex justify-center items-center cursor-pointer transition hover:shadow-lg"
              >
                <span className="text-white">
                  {isLoading ? "Loading..." : "Create"}
                </span>
              </button>
            </div>
          </div>
        </div>

        <div className="bg-white/10 rounded-lg w-72 h-72 sm:w-[29rem] sm:h-[29rem] lg:transform lg:translate-y-44 relative flex justify-center items-center backdrop-blur-3xl shadow-md mb-10 lg:mb-0">
          {images && (
            <>
              <Image src={images.url} alt="Art" fill className="rounded-md" />
              <div className="absolute w-full h-full -z-10 blur-3xl opacity-80">
                <Image src={images.url} alt="Art" fill />
              </div>
              <div className="absolute bottom-0 left-0 w-full h-20 bg-white/10 backdrop-blur-lg rounded-b-md flex justify-evenly items-center">
                <Link href={images.url} legacyBehavior>
                  <a
                    className="px-3 py-2 rounded-full text-[#111526] border border-[#111526] hover:shadow-lg"
                    target="_blank"
                  >
                    Open
                  </a>
                </Link>
                <button
                  onClick={handleGenerateArtAgain}
                  className="bg-[#111526] text-white px-3 py-2 rounded-full hover:shadow-lg"
                >
                  Create Again
                </button>
                <button
                  onClick={() => handleDownloadImage()}
                  className="px-3 py-2 rounded-full text-[#111526] border border-[#111526] hover:shadow-lg"
                >
                  Save
                </button>
              </div>
            </>
          )}
          <div className="font-black text-5xl text-center text-[#111526]">
            YOUR
            <br />
            ART
          </div>
          {isLoading && (
            <>
              <div className="w-full h-1 bg-white z-50 absolute animationGenerate left-0 rounded-full shadow-2xl shadow-white flex items-center justify-center">
                <div className="bg-white text-sm px-2 rounded-full text-gray-600">
                  Generating...
                </div>
              </div>
              <div className="absolute z-40 w-full h-full top-0 left-0 bg-linear rounded-md"></div>
            </>
          )}
        </div>
      </header>
      <main className="mx-auto container mt-10 pl-5 lg:pl-0">
        <h1 className="font-bold text-gray-800 text-2xl mb-5">Recent Arts</h1>
        <div className="flex flex-row flex-wrap w-full lg:w-2/4 gap-5 mb-5">
          {recentImages &&
            recentImages.reverse().map((item: Image, index: number) => {
              return (
                <RecentImage
                  key={index}
                  image={item}
                  handleSelect={handleSelectSavedImage}
                />
              );
            })}
        </div>
      </main>
      <footer className="w-full flex justify-center items-center text-gray-700 dark:text-gray-300 flex-col fade-in-down-delay-2 font-bold my-5">
        <Link href="https://github.com/ADEV-00" legacyBehavior>
          <a target="_blank">
            Made by <span className="text-teal-500 font-black">ADEV</span>
          </a>
        </Link>
        <div></div>
      </footer>
    </div>
  );
};

export default Home;
